### ISSUE TITLE
Issues w/ binary artifact

### ISSUE THREAD

**Issue by michaelcsilva** [serhuz/dropwizard-morphia#1]
Hi.  Thanks for publishing dropwizard-morphia.  I have tried to use it in a project I'm working on and ran into an issue.  The artifact on bintray for the latest version downloads with dashes in the name (e.g.: ~/.m2/repository/xyz/randomcode/dropwizard-morphia/1.2.0-1)

The dashes are not valid for importing.  i.e. this causes an error
import xyz.randomcode.dropwizard-morphia.MongoConfiguration;

The example code you provide uses underscores, but that leads to the artifact not being found:

import xyz.randomcode.dropwizard_morphia.MongoConfiguration;

Apologies if this is some noob mistake on my part.

**Comment by serhuz** [comment]
Dashes are used for `artifactId`. The actual `.jar` file contains `dropwizard_morphia` package, because as you correctly mentioned, dashes are illegal in package names. 

It appears that artifact isn't correctly resolved in your project by Maven. 

Try adding these lines to your `pom.xml` directly under `<project>` tag:
```xml
<repositories>
    <repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>bintray-serhuz-maven</id>
        <name>bintray</name>
        <url>http://dl.bintray.com/serhuz/maven</url>
    </repository>
</repositories>
```

Then invoke `mvn compile` and see if your project compiles.

**Comment by michaelcsilva** [comment]
Thanks for the help.  i started again w/ your example app and was able to get the right settings into my pom.
